apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: jenkins-scratch-data-pv-claim
    namespace: kubernetes-plugin
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 50Mi
    # selector:
    #     matchLabels:
    #         pv: jenkins-scratch-data-pv