apiVersion: v1
kind: List
items:
    - apiVersion: v1
      kind: PersistentVolume
      metadata:
        name: gitlab-data
        namespace: cip-kube
      spec:
        capacity: 
            storage: 100Mi
        hostPath:
            path: /opt/gitlab/data
        accessModes:
            - ReadWriteOnce

    - apiVersion: v1
      kind: PersistentVolume
      metadata:
        name: gitlab-logs
        namespace: cip-kube
      spec:
        capacity: 
            storage: 50Mi
        hostPath:
            path: /opt/gitlab/logs
        accessModes:
            - ReadWriteOnce

    - apiVersion: v1
      kind: PersistentVolume
      metadata:
        name: gitlab-config
        namespace: cip-kube
      spec:
        capacity: 
            storage: 50Mi
        hostPath:
            path: /opt/gitlab/config
        accessModes:
            - ReadWriteOnce

    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: gitlab-data
        namespace: cip-kube
      spec:
        accessModes:
            - ReadWriteOnce
        resources:
            requests: 
                storage: 100Mi
                    
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: gitlab-logs
        namespace: cip-kube
      spec:
        accessModes:
            - ReadWriteOnce
        resources:
            requests: 
                storage: 50Mi
                    
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: gitlab-config
        namespace: cip-kube
      spec:
        accessModes:
            - ReadWriteOnce
        resources:
            requests: 
                storage: 50Mi
            
    - apiVersion: extensions/v1beta1
      kind: Deployment
      metadata:
        name: gitlab
        namespace: cip-kube
      spec:
        replicas: 1
        template:
            metadata:
                name: gitlab
                labels:
                    run: gitlab
            spec:
                containers: 
                    - name: gitlab
                      image: gitlab/gitlab-ce:8.14.5-ce.0
                      ports:
                        - containerPort: 80
                        - containerPort: 443
                        - containerPort: 22
                      volumeMounts:
                        - name: gitlab-data
                          mountPath: /var/opt/gitlab
                        - name: gitlab-logs
                          mountPath: /var/log/gitlab
                        - name: gitlab-config
                          mountPath: /etc/gitlab
                volumes:
                    - name: gitlab-data
                      persistentVolumeClaim:
                        claimName: gitlab-data
                    - name: gitlab-logs
                      persistentVolumeClaim:
                        claimName: gitlab-logs
                    - name: gitlab-config
                      persistentVolumeClaim:
                        claimName: gitlab-config

    - apiVersion: v1
      kind: Service
      metadata:
        name: gitlab
        namespace: cip-kube
      spec:
        type: NodePort
        selector:
            run: gitlab
        ports:
            - name: http
              port: 80
            - name: https
              port: 443
            - name: ssl
              port: 22