---
apiVersion: v1
kind: List
items: 
    - apiVersion: v1
      kind: PersistentVolume
      metadata:
          name: jenkins-data
          namespace: cip-kube
      spec:
          hostPath:
              path: /opt/jenkins/data
          capacity:
              storage: 50Mi
          accessModes:
              - ReadWriteOnce

    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
          name: jenkins-data
          namespace: cip-kube
      spec:
          accessModes:
              - ReadWriteOnce
          resources:
              requests:
                  storage: 50Mi

    - apiVersion: extensions/v1beta1
      kind: Deployment
      metadata:
          name: jenkins
          namespace: cip-kube
      spec:
          replicas: 2
          template:
              metadata:
                  labels:
                      run: jenkins
                      jenkins.version: 2.31.1
              spec:
                  containers:
                    - name: jenkins
                      image: jgsqware/jenkins-kubernetes-minikube:2.32.1-alpine
                      ports:
                        - containerPort: 8080
                      volumeMounts:
                        - mountPath: /var/jenkins_home
                          name: jenkins-data
                  volumes:
                    - name: jenkins-data
                      persistentVolumeClaim:
                          claimName: jenkins-data
    
    - apiVersion: v1
      kind: Service
      metadata: 
          name: jenkins
          namespace: cip-kube
      spec:
          type: NodePort
          ports:
              - port: 8080
          selector: 
              run: jenkins