apiVersion: v1
kind: List
items:
    - apiVersion: v1
      kind: PersistentVolume
      metadata:
        name: nexus-data
        namespace: cip-kube
      spec:
        capacity:
            storage: 3Gi
        hostPath:
            path: /opt/nexus/data
        accessModes:
            - ReadWriteOnce
    
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: nexus-data
        namespace: cip-kube
      spec:
        accessModes:
            - ReadWriteOnce
        resources:
            requests:
                storage: 3Gi
    
    - apiVersion: extensions/v1beta1
      kind: Deployment
      metadata:
        name: nexus
        namespace: cip-kube
      spec:
        replicas: 1
        template:
            metadata:
                name: nexus
                namespace: cip-kube
                labels:
                    run: nexus
            spec:
                containers:
                    - name: nexus
                      image: clearent/nexus:3.2.0-01
                      ports:
                        - containerPort: 8081
                      volumeMounts:
                        - name: nexus-data
                          mountPath: /nexus-data
                      env:
                        - name: JAVA_MAX_MEM
                          value: 2048M
                volumes:
                    - name: nexus-data
                      persistentVolumeClaim:
                        claimName: nexus-data

    - apiVersion: v1
      kind: Service
      metadata:
        name: nexus
        namespace: cip-kube
      spec:
        type: NodePort
        ports:
            - port: 8081
        selector:
            run: nexus