---
apiVersion: v1
kind: List
items: 
    - apiVersion: extensions/v1beta1
      kind: Deployment
      metadata:
          name: jenkins
          namespace: jenkins-blue-green
      spec:
          replicas: 2
          template:
              metadata:
                  labels:
                      run: jenkins
                      jenkins.version: 2.19.3
              spec:
                  containers:
                    - name: jenkins
                      image: jgsqware/jenkins-kubernetes-minikube:2.19.3-alpine
                      ports:
                        - containerPort: 8080
                      volumeMounts:
                        - mountPath: /var/jenkins_home
                          name: jenkins-data
                  volumes:
                    - name: jenkins-data
                      persistentVolumeClaim:
                          claimName: jenkins-data
    
    - apiVersion: v1
      kind: Service
      metadata: 
          name: jenkins
          namespace: jenkins-blue-green
      spec:
          type: NodePort
          ports:
              - port: 8080
          selector: 
              run: jenkins